%{
For the Sandra Project, I investigated some exciting properties of the
Lorenz '63 system, including using data assimilation based off of initial
data (which was generated via the Adams-Bashforth method). The files have
been vastly simplified and cleaned up.

The main functions I used were the initmatrix, DAadbash, and adbash (which
is now mostly obsolete because of DAadbash). One change I made to the
DAadbash function was to make it detect which version it should run---regular 
Adams-Bashforth, or with data assimilation. If it detects less than two variables, 
it tries to run regular adbash. If there's two or more, it tries to run data-assimilated
Adams-Bashforth, using the second variable as the "data" to nudge the model
in the right direction.

The initmatrix function was made to make it easy to reset the large
matrices I was using to store the data generated by Adams-Bashforth. 


When I was choosing values for ux, uy, and uz, I made sure that they had
values less than 2/0.0001=20000, which is not hard to satify.

To answer the part about what happens if we do not have position data for
two of the variables to enter into the data assimilation scheme, you can
(temporarily) set the mus (the ux,uy,uz) to zero to indicate which you will
not be data assimilating with. I.e., if Sandra lost her y and z data, uy 
and uz should be set to zero. 

For this to work you can save
those variables to the Sandra_Vars.mat file. Then, you can run adbash on
Pos, and then run DAadbash on daPos with Pos as the second argument, to
achieve this. I'm sure there's a better way, but for the moment, this is
what I have. This can be done for each variable, and we will see that if
there is only x data or y data, Sandra does not need to redo her experiment
because  the data assimilation from one variable synchronizes the others to
the right path. However, if only z data is left, this will not work.

Some notes on doing that: I found that I had to make the value of ux
sufficiently small (while uy and uz were zero) to get the scheme to
converge in a nice way. 10 was too chunky, 100 was worse, so I settled on
ux=1.

Unfortunately, I could not get the data to be reproduced by data
assimilation with only one column of position data! This is something I
hope to discuss in the next meeting.

-Xander

%}